const { GoogleGenAI } = require("@google/genai")
const { z } = require("zod")
const { zodToJsonSchema } = require("zod-to-json-schema")
const puppeteer = require("puppeteer")


const ai = new GoogleGenAI({
	apiKey: process.env.GOOGLE_API_KEY
})


const interviewReportSchema = z.object({
	matchscore: z.number().describe("The match score between the candidate and the job describe, on a scale of 0 to 100, where 100 means a perfect match and 0 means no match at all"),
	technicalQuestions: z.array(z.object({
		question: z.string().describe("The technical question can be asked in the interview"),
		intention: z.string().describe("The intention of the interview behind asking this question"),
		answer: z.string().describe("How to answer this question, what points to be cover, what approaches to take etc.")
	})).describe("Technical questions that can be asked in the interview along with the intention behind asking this question and how to answer it"),
	behavioralQuestions: z.array(z.object({
		question: z.string().describe("The technical question can be asked in the interview"),
		intention: z.string().describe("The intention of the interview behind asking this question"),
		answer: z.string().describe("How to answer this question, what points to be cover, what approaches to take etc.")
	})).describe("Behavioural questions that can be asked in the interview along with the intention behind asking this question and how to answer it"),
	skillGap: z.array(z.object({
		skill: z.string().describe("The skill that the candidate is lacking"),
		severity: z.enum(["low", "medium", "high"]).describe("The severity of the skill gap, i.e., how important is it for the candidate to have this skill for the job they are applying for"),
	})).describe("List of skills that the candidate is lacking along with the severity"),
	preparationPlan: z.array(z.object({
		day: z.number().describe("The day of the preparation plan, e.g., day 1, day 2, etc."),
		focus: z.string().describe("The focus of the preparation for that day, e.g., data structures, system design, etc."),
		tasks: z.array(z.string()).describe("The tasks to be done on that day for preparation, e.g., solve 5 coding problems, read a chapter of a book, etc.")
	})).describe("A preparation plan for the candidate to follow in order to prepare for the interview effectively."),
	title: z.string().describe("The title of the job for which the interview report is generated"),

})

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {

	const prompt = `
You are an expert interviewer.

Return ONLY valid JSON. No text, no explanation.

STRICT FORMAT (must follow exactly):

{
  "title": "string",
  "matchscore": number,
  "technicalQuestions": [
    {
      "question": "string",
      "intention": "string",
      "answer": "string"
    }
  ],
  "behavioralQuestions": [
    {
      "question": "string",
      "intention": "string",
      "answer": "string"
    }
  ],
  "skillGap": [
    {
      "skill": "string",
      "severity": "low"
    }
  ],
  "preparationPlan": [
    {
      "day": 1,
      "focus": "string",
      "tasks": ["string"]
    }
  ]
}



Resume:
${resume}

Self Description:
${selfDescription}

Job Description:
${jobDescription}
`

	const response = await ai.models.generateContent({
		model: "gemini-3-flash-preview",
		contents: prompt,
		config: {
			responseMimeType: "application/json",
			responseSchema: zodToJsonSchema(interviewReportSchema)
		}
	})
	const raw = response.text

	if (!raw) {
		throw new Error("No AI response")
	}

	const result = JSON.parse(raw)

	//console.log("AI FINAL RESPONSE:", result)
	return result

}

async function generatePDFfromHTML(htmlContent) {
	const browser = await puppeteer.launch()
	const page = await browser.newPage()
	await page.setContent(htmlContent, { waitUntil: 'networkidle0' })

	const pdfBuffer = await page.pdf({ format: 'A4', margin: {
		top: '20mm',
		bottom: '20mm',
		left: '15mm',
		right: '15mm'
	}})

	await browser.close()

	return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

	const resumePdfSchema = z.object({
		html: z.string().describe("The HTML content of the resume which can be converted to PDF using a library like puppeteer")
	})

	const prompt = `Generate resume for a candidate with the following details:
	Resume: ${resume}
	Self Description: ${selfDescription}
	Job Description: ${jobDescription}

	                   the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
`


	const response = await ai.models.generateContent({
		model: "gemini-3-flash-preview",
		contents: prompt,
		config: {
			responseMimeType: "application/json",
			responseSchema: zodToJsonSchema(resumePdfSchema)
		}
	})

	const jsonContent = JSON.parse(response.text)
	const pdfBuffer = await generatePDFfromHTML(jsonContent.html)

	return pdfBuffer
}


module.exports = { generateInterviewReport, generateResumePdf }